# Generated by Django 5.0.2 on 2024-04-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
